add rc variable nfs_server_maxio
git-svn-id: https://svn.code.sf.net/p/xigmanas/code/trunk@9139 beaaabd7-781f-4c1e-bc4d-5cfe25df7511

diff --git a/etc/rc.d/nfsd b/etc/rc.d/nfsd
--- a/etc/rc.d/nfsd
+++ b/etc/rc.d/nfsd
@@ -43,9 +43,17 @@ nfsd_precmd()
 	# oids are available.
 	load_kld nfsd
 
+	if [ -n "${nfs_server_maxio}" ]; then
+		if ! sysctl vfs.nfsd.srvmaxio=${nfs_server_maxio} >/dev/null; then
+			warn "Failed to set server max I/O"
+		fi
+	fi
+
 	if checkyesno nfs_reserved_port_only; then
 		echo 'NFS on reserved port only=YES'
 		sysctl vfs.nfsd.nfs_privport=1 > /dev/null
+	else
+		sysctl vfs.nfsd.nfs_privport=0 > /dev/null
 	fi
 
 	if checkyesno nfsv4_server_enable; then
