update
git-svn-id: https://svn.code.sf.net/p/xigmanas/code/trunk@7393 beaaabd7-781f-4c1e-bc4d-5cfe25df7511

diff --git a/etc/rc.d/nfsd b/etc/rc.d/nfsd
--- a/etc/rc.d/nfsd
+++ b/etc/rc.d/nfsd
@@ -6,12 +6,12 @@
 #
 # Remote NFS server
 #
-# $FreeBSD: /etc/rc.d/nfsd	Revision r302406
+# $FreeBSD: /stable/12/libexec/rc/rc.d/nfsd	Revision r346910
 # Changes: modified for XigmaNAS®, removed REQUIRE: gssd
 #
 
 # PROVIDE: nfsd
-# REQUIRE: mountd hostname nfsuserd
+# REQUIRE: mountcritremote mountd hostname nfsuserd
 # KEYWORD: nojail shutdown
 # XQUERY: -i "count(//nfsd/enable) > 0" -o "0" -b
 # RCVAR: nfs_server
@@ -24,6 +24,7 @@ name="nfsd"
 desc="Remote NFS server"
 rcvar=nfs_server_enable
 command="/usr/sbin/${name}"
+nfs_server_vhost=""
 
 # Customize number of server processes/daemons
 nfs_server_flags=`/usr/local/bin/xml sel -t -v "concat('-u -t -n ',//nfsd/numproc)" ${configxml_file} | /usr/local/bin/xml unesc`
@@ -35,30 +36,31 @@ sig_stop="USR1"
 
 nfsd_precmd()
 {
-		rc_flags="${nfs_server_flags}"
+	local	_vhost
+	rc_flags="${nfs_server_flags}"
 
-		# Load the modules now, so that the vfs.nfsd sysctl
-		# oids are available.
-		load_kld nfsd
+	# Load the modules now, so that the vfs.nfsd sysctl
+	# oids are available.
+	load_kld nfsd
 
-		if checkyesno nfs_reserved_port_only; then
-			echo 'NFS on reserved port only=YES'
-			/sbin/sysctl vfs.nfsd.nfs_privport=1 > /dev/null
-		fi
+	if checkyesno nfs_reserved_port_only; then
+		echo 'NFS on reserved port only=YES'
+		sysctl vfs.nfsd.nfs_privport=1 > /dev/null
+	fi
 
-		if checkyesno nfsv4_server_enable; then
-			/sbin/sysctl vfs.nfsd.server_max_nfsvers=4 > /dev/null
-			if ! checkyesno nfsuserd_enable  && \
-			    ! /etc/rc.d/nfsuserd forcestatus 1>/dev/null 2>&1
-			then
-				if ! force_depend nfsuserd; then
-					err 1 "Cannot run nfsuserd"
-				fi
+	if checkyesno nfsv4_server_enable; then
+		sysctl vfs.nfsd.server_max_nfsvers=4 > /dev/null
+		if ! checkyesno nfsuserd_enable  && \
+			   ! /etc/rc.d/nfsuserd forcestatus 1>/dev/null 2>&1
+		then
+			if ! force_depend nfsuserd; then
+				err 1 "Cannot run nfsuserd"
 			fi
-		else
-			echo 'NFSv4 is disabled'
-			/sbin/sysctl vfs.nfsd.server_max_nfsvers=3 > /dev/null
 		fi
+	else
+		echo 'NFSv4 is disabled'
+		sysctl vfs.nfsd.server_max_nfsvers=3 > /dev/null
+	fi
 
 	if ! checkyesno rpcbind_enable  && \
 	    ! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
@@ -70,6 +72,8 @@ nfsd_precmd()
 	    ! /etc/rc.d/mountd forcestatus 1>/dev/null 2>&1
 	then
 		force_depend mountd || return 1
+	if [ -n "${nfs_server_vhost}" ]; then
+		command_args="-V \"${nfs_server_vhost}\""
 	fi
 	return 0
 }
