Update devcpu-data-amd-20211109 and split ports
git-svn-id: https://svn.code.sf.net/p/xigmanas/code/trunk@8795 beaaabd7-781f-4c1e-bc4d-5cfe25df7511

diff --git a/build/ports/devcpu-data-amd/files/microcode_update.in b/build/ports/devcpu-data-amd/files/microcode_update.in
--- a/build/ports/devcpu-data-amd/files/microcode_update.in
+++ b/build/ports/devcpu-data-amd/files/microcode_update.in
@@ -20,7 +20,7 @@
 # microcode_update_datadir (str):	Directory, microcode updates stored in.
 #					Default is "%%DATADIR%%"
 # microcode_update_cpus (str):		A list of cpus to update on startup, or "ALL" for all.
-#					Example: microcode_update_cpus_cpus="0 CPU0"
+#					Example: microcode_update_cpus="0 1"
 #					Set to "ALL" by default.
 # microcode_update_flags (str):		Flags for cpucontrol(8).
 
@@ -48,29 +48,29 @@ microcode_update_prepare()
 microcode_update_start()
 {
 	echo "Updating CPU Microcode..."
-	if [ "${microcode_cpus}" = "ALL" ]; then
+	if [ "${microcode_update_cpus}" = "ALL" ]; then
 		ncpu=`/sbin/sysctl -n hw.ncpu`
 		cpus=`jot ${ncpu} 0`;
 	else
-		cpus=${microcode_cpus}
+		cpus=${microcode_update_cpus}
 	fi
 	for i in ${cpus}; do
 		${CMT} -u ${microcode_update_flags} \
-		  -d "${microcode_update_datadir}" /dev/cpuctl${i} 2>&1 | \
-		  logger -p daemon.notice -t microcode_update || \
-		  (echo "Microcode Update Failed." && exit 1)
+                    -d "${microcode_update_datadir}" /dev/cpuctl${i} 2>&1 | \
+                    logger -p daemon.notice -t microcode_update || \
+		    (echo "Microcode Update Failed." && exit 1)
 	done
-	if [ "${microcode_cpus}" = "ALL" ]; then
-		CPUCONTROL_UPDATED=$(cpucontrol -h 2>&1 | grep -q -- -e; echo $?)
-		if [ ${CPUCONTROL_UPDATED} -ne 0 ]; then
-			echo "Please update your system in order to update CPU microcode."
+	if [ "${microcode_update_cpus}" = "ALL" ]; then
+                CPUCONTROL_UPDATED=$(cpucontrol -h 2>&1 | grep -q -- -e; echo $?)
+                if [ ${CPUCONTROL_UPDATED} -ne 0 ]; then
+                        echo "Please update your system in order to update CPU microcode."
                 else
 			${CMT} -e /dev/cpuctl0 >/dev/null 2>&1
-		   if [ $? -ne 0 ]; then
-			echo "Re-evalutation of CPU flags Failed."
-			exit 1
-	           fi
-	     fi
+			if [ $? -ne 0 ]; then
+				echo "Re-evalulation of CPU flags Failed."
+				exit 1
+			fi
+                fi
 	fi
 	echo "Done."
 }
@@ -78,9 +78,19 @@ microcode_update_start()
 load_rc_config $name
 
 # Set default values
+if [ -n "${microcode_cpus}" ]; then
+	if [ -n "${microcode_update_cpus}" ]; then
+		echo "Warning: Ignoring deprecated rc variable, microcode_cpus."
+	else
+		echo "Warning: rc variable microcode_cpus is deprecated.
+Warning: Set microcode_udpate_cpus instead."
+		microcode_update_cpus="${microcode_cpus}"
+        fi
+fi
+
 : ${microcode_update_enable="NO"}
 : ${microcode_update_datadir="/usr/local/share/cpucontrol"}
-: ${microcode_cpus="ALL"}
+: ${microcode_update_cpus="ALL"}
 : ${microcode_update_flags=""}
 
 run_rc_command "$1"
