Wait for platform device/label to be ready
git-svn-id: https://svn.code.sf.net/p/xigmanas/code/trunk@7926 beaaabd7-781f-4c1e-bc4d-5cfe25df7511

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -49,6 +49,22 @@ export BOOT_LOWMEM
 export BOOT_LIVECD
 #/bin/kenv -q boot_lowmem=${BOOT_LOWMEM} > /dev/null
 
+# Max wait retries in secs for a platform to be ready.
+RETRY=0
+RETRY_MAX=15
+
+platform_wait() {
+	# Wait for the platform device/label to be ready before halt.
+	if ! /sbin/glabel status -s | /usr/bin/grep -q "${BOOT_PLATFORM}"; then
+		if [ "${RETRY}" -eq "${RETRY_MAX}" ]; then
+			echo "Waiting for ${BOOT_PLATFORM} retries exhausted!"
+			sleep 30; halt
+		fi
+		RETRY=$(/bin/expr ${RETRY} + 1); sleep 1
+		platform_wait
+	fi
+}
+
 case ${PLATFORM} in
 	*-full)
 		if ! zpool list -H -o bootfs | grep -qw "${ZROOT}/ROOT"; then
@@ -68,9 +84,11 @@ case ${PLATFORM} in
 		md=$(/sbin/mdconfig -t malloc -o compress -s ${MDLOCALSIZE})
 		case ${PLATFORM} in
 			*-liveUSB)
+				BOOT_PLATFORM="ufs/liveboot"
+				platform_wait
 				# To deal with "the secondary GPT header is not in the last LBA."
-				SYSUFS=$(glabel status | grep -q "ufs\/liveboot"; echo $?)
-				GPTUSB=$(glabel status | awk '/gpt\/usbsysdisk/{print $3}' | tr -d 'p3')
+				SYSUFS=$(glabel status -s | grep -q "ufs\/liveboot"; echo $?)
+				GPTUSB=$(glabel status -s | awk '/gpt\/usbsysdisk/{print $3}' | tr -d 'p3')
 				if [ "${SYSUFS}" -eq 0 ]; then
 					if [ -n "${GPTUSB}" ]; then
 						if gpart show "${GPTUSB}" | grep -q "CORRUPT"; then
@@ -118,6 +136,8 @@ case ${PLATFORM} in
 				/sbin/umount /mnt
 				;;
 			*-embedded)
+				BOOT_PLATFORM="embboot"
+				platform_wait
 				root=$(/sbin/glabel status -s | /usr/bin/awk '/embboot/{print $3;exit 0}')
 				gptswap=$(/sbin/glabel status -s | /usr/bin/awk '/gptswap/{print $3;exit 0}')
 				if [ -z "${root}" ]; then
@@ -162,6 +182,8 @@ case ${PLATFORM} in
 				;;
 			*-liveCD)
 				BOOT_LIVECD=1
+				BOOT_PLATFORM="LiveCD"
+				platform_wait
 				root=$(/sbin/glabel status -s | /usr/bin/awk '/LiveCD/{print $3;exit 0}')
 				if [ -z "${root}" ]; then
 					echo "can't determine rootfs"
