avoid core installation on memory device
git-svn-id: https://svn.code.sf.net/p/xigmanas/code/trunk@6215 beaaabd7-781f-4c1e-bc4d-5cfe25df7511

diff --git a/build/ports/mariadb102/files/mysqldb.in b/build/ports/mariadb102/files/mysqldb.in
--- a/build/ports/mariadb102/files/mysqldb.in
+++ b/build/ports/mariadb102/files/mysqldb.in
@@ -68,7 +68,12 @@ mysqldb_mkconf()
 	unlink /var/db/mysql
 	ln -s "${mariadbhomedir}" /var/db/mysql
 	if [ ! -d "${mariadbhomedir}/mysql/." ]; then
-		/usr/local/bin/mysql_install_db --basedir=/usr/local --datadir=${mariadbhomedir} --force
+		if [ "$(df ${mariadbhomedir} | grep -E '/dev/x?md[0-9]|tmpfs')" ]; then
+			echo "Home folder on memory disk detected, unable to install core."
+			exit 1
+		else
+			/usr/local/bin/mysql_install_db --basedir=/usr/local --datadir=${mariadbhomedir} --force
+		fi
 	fi
 	chown -R ${mysql_user}:${mysql_group} ${mariadbhomedir}
 
