Upgrade devcpu-data to 1.14.
git-svn-id: https://svn.code.sf.net/p/xigmanas/code/trunk@5074 beaaabd7-781f-4c1e-bc4d-5cfe25df7511

diff --git a/build/ports/devcpu-data/files/microcode_update.in b/build/ports/devcpu-data/files/microcode_update.in
--- a/build/ports/devcpu-data/files/microcode_update.in
+++ b/build/ports/devcpu-data/files/microcode_update.in
@@ -56,9 +56,19 @@ microcode_update_start()
 	fi
 	for i in ${cpus}; do
 		${CMT} -u ${microcode_update_flags} \
-		    -d "${microcode_update_datadir}" /dev/cpuctl${i} || \
-		    (echo "Microcode Update Failed." && exit 1)
+		  -d "${microcode_update_datadir}" /dev/cpuctl${i} 2>&1 | \
+		  logger -p daemon.notice -t microcode_update || \
+		  (echo "Microcode Update Failed." && exit 1)
 	done
+	if [ "${microcode_cpus}" = "ALL" ]; then
+	       for i in ${cpus}; do
+		   ${CMT} -e /dev/cpuctl${i} >/dev/null 2>&1
+		   if [ $? -ne 0 ]; then
+		         echo "Re-evalutation of CPU flags Failed."
+		         exit 1
+	           fi
+	     done
+	fi
 	echo "Done."
 }
 
