code change
git-svn-id: https://svn.code.sf.net/p/xigmanas/code/trunk@5079 beaaabd7-781f-4c1e-bc4d-5cfe25df7511

diff --git a/build/ports/devcpu-data/files/microcode_update.in b/build/ports/devcpu-data/files/microcode_update.in
--- a/build/ports/devcpu-data/files/microcode_update.in
+++ b/build/ports/devcpu-data/files/microcode_update.in
@@ -61,11 +61,14 @@ microcode_update_start()
 		  (echo "Microcode Update Failed." && exit 1)
 	done
 	if [ "${microcode_cpus}" = "ALL" ]; then
-	       for i in ${cpus}; do
-		   ${CMT} -e /dev/cpuctl${i} >/dev/null 2>&1
+		CPUCONTROL_UPDATED=$(cpucontrol -h 2>&1 | grep -q -- -e; echo $?)
+		if [ ${CPUCONTROL_UPDATED} -ne 0 ]; then
+			echo "Please update your system in order to update CPU microcode."
+                else
+			${CMT} -e /dev/cpuctl0 >/dev/null 2>&1
 		   if [ $? -ne 0 ]; then
-		         echo "Re-evalutation of CPU flags Failed."
-		         exit 1
+			echo "Re-evalutation of CPU flags Failed."
+			exit 1
 	           fi
 	     done
 	fi
